print("Wat is uw volledige naam?")
naam = input()
print("Wat is uw adres?")
adres = input()
print("Wat is uw postcode?")
postcode = input()
print("Wat is uw woonplaats?")
woonplaats = input()

print(" ----------------------------------------------------")
print("|  Naam      : "+str(naam))                
print("|  Adres     : "+str(adres))     
print("|  Postcode  : "+str(postcode))                     
print("|  Woonplaats: "+str(woonplaats))                          
print(" ----------------------------------------------------")